# fly.toml app configuration file generated for uniasistan-api on 2025-06-08T12:59:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uniasistan-api'
primary_region = 'fra'

[build]
  dockerfile = "C:\Users\cihan\Desktop\UniAsistan\Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
  swap_size_mb = 512


[mounts]
  source = "uniasistan_data"
  destination = "/data"