# fly.toml app configuration file generated for uniasistan on 2025-06-11T01:50:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uniasistan'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = 512
  cpu_kind = 'shared'
  cpus = 1
